# Generated by Django 4.2.2 on 2023-06-10 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagarapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='origin',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='pagarapi.account'),
        ),
    ]
