# Generated by Django 4.2.2 on 2023-06-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagarapi', '0002_remove_transaction_origin_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='motive',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
