# Generated by Django 4.2.2 on 2023-06-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagarapi', '0003_transaction_motive_transaction_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=24),
        ),
    ]
